language: minimal

python:
    - '3.6'

compiler:
    - g++
   
cache:
    ccache: true
    pip: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip
  - pip3 install --upgrade pip
  - sudo pip3 install setuptools
  - sudo pip3 install python-coveralls
  - sudo pip3 install tensorflow
  - sudo pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

install:
    - sudo pip3 install -e . -r requirements.txt
    - df -h

script:
  - coverage run -m unittest discover

after_success:
  - codecov
  - coveralls