language: minimal

compiler:
    - g++
   
cache:
    ccache: true
    pip: true

before_install:
  - sudo apt-get update
  - sudo apt-get -y install python3-pip libhdf5-dev libhdf5-serial-dev
  - sudo -H pip3 install --upgrade pip
  - sudo -H pip3 install setuptools
  - sudo -H pip3 install python-coveralls
  - sudo -H pip3 install tensorflow
  - sudo -H pip3 install torch
  - python3 --version
  - which python3
  - pip3 --version
  - which pip3

install:
    - sudo -H pip3 install -e . -r requirements.txt
    - sudo -H pip3 install -U scipy pandas matplotlib astropy
    - python3 -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
    - python3 -c "import torch"
    - python3 -c "import scipy"
    - python3 -c "import unittest"
    - python3 -c "import shutil"
    - python3 -c "import numpy as np;print(np.zeros((3, 2)))"
    - df -h

script:
  - coverage run -m unittest discover

after_success:
  - codecov
  - coveralls