language: python

python:
    - '3.6'

compiler:
    - g++
   
cache:
    ccache: true
    pip: true

before_install:
  - which pip
  - pip install -q coveralls
  - pip install -q python-coveralls
  - pip install -q tensorflow
  - pip install -q torch 

install:
  - pip install -e . -r requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - codecov
  - coveralls