language: minimal

python:
    - '3.6'

compiler:
    - g++
   
cache:
    ccache: true
    pip: true

before_install:
  - pip3 install python-coveralls
  - pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-2.0.0-cp36-cp36m-manylinux2010_x86_64.whl
  - pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html

install:
    - "pip3 install -e . -r requirements.txt"
    - df -h

script:
  - coverage run -m unittest discover

after_success:
  - codecov
  - coveralls