language: python

python:
    - '3.6'

compiler:
    - g++
   
cache:
    ccache: true
    pip: true

before_install:
  - pip install coveralls
  - pip install python-coveralls

install:
    - "pip install -e . -r requirements.txt"

script:
  - coverage run -m unittest discover

after_success:
  - codecov
  - coveralls